project: 
  type: website

website:
  page-navigation: true
  title: "MTBAP Landing Page"
  site-url: "https://pifsc-protected-species-division.github.io/MTBAP-Landing-Page/"
  repo-url: "https://github.com/PIFSC-Protected-Species-Division/MTBAP-Landing-Page"
  repo-actions: [edit, source, issue]
  favicon: content/images/favicon.ico

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"

  sidebar:
    background: "#D9E3E4"
    logo: "content/images/psd_logo_NB.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.fisheries.noaa.gov/pacific-islands/population-assessments/population-assessment-field-camps-papahanaumokuakea-marine-national-monument
        text: "NOAA Population Assessment Field Camps"
        target: _blank
      - icon: github
        href: https://github.com/PIFSC-Protected-Species-Division/PMNM-ARCamps-Manual
        text: "Github Repository"

    style: "docked"
    search: true
    collapse-level: 0
    contents:
      - section: "About Us"
        contents:
          - href: index.qmd
            text: Overview
          - href: content/TeamMembers.qmd
            text: Team Members

      - section: "Publications"
        contents:
          - href: content/PeerReviewed.qmd
            text: Peer-Reviewed Articles
          - href: content/Reports.qmd
            text: Technical Reports
          - href: content/OutreachMedia.qmd
            text: Outreach & Media

      - section: "Resources"
        contents:
          - href: content/Onboarding.qmd
            text: Onboarding
          - href: content/SOPs.qmd
            text: Standard Operating Procedures
          - href: content/Forms.qmd
            text: Forms

format:
  html:
    theme: cosmo
    css: content/styles.css

