---
title: "Standard Operating Procedures"
format: html
---

Protocols and guidelines of the Marine Turtle Biology and Assessment Program.

# Field Protocols
- [Blood Collection](https://docs.google.com/document/d/175WWs7nJCbN4vPVtJ-kJ28JzwAph7M1LrqqlMm62uHs/edit?tab=t.0)  
- [Honu Count Data Protocol](https://docs.google.com/document/d/1uZfmYNalu5zGVWvRlkEi2rBLu58McFhFzK4mxDFt-GA/edit?tab=t.0)  
- [Instructions for Turtle Capture Box](https://docs.google.com/document/d/1aUnTikSxbZ3MWk6nviODJNt_OHIUq1jo/edit)  
- [Marine Turtle Excavation Protocols](https://docs.google.com/document/d/143xNUouMSboRwuWR9Vmy5i2DUN36E_ELpjDeoYn7ISA/edit?tab=t.0)  
- [Marine Turtle Hatchling Sampling](https://docs.google.com/document/d/1tPPKQYbSHgpoI8VajsWwP8yidL_RH2sj/edit)  
- [Marine Turtle Nest Probing Protocols](https://docs.google.com/document/d/1uwN9JQ_nuuXtkl_eFIMoW5zIkW87yBf-/edit)  
- [Photographing Turtles](https://docs.google.com/document/d/1knPcXL_77P8vvoVHrmnd_q8DlO3pQZD7LTkVDjgvw6E/edit?tab=t.0)  
- [2025 Marine Turtle Field Research Manual](https://docs.google.com/document/d/1Y872yJlu62dvjkCeobu9P0QEPV0BhpBKfdPuW4Ll49k/edit?tab=t.0)  

# Lab Protocols
- [Facial Recognition](https://docs.google.com/document/d/1l8qrhz6Bk3yL9UdzOML5Kq6yWj2Uctlq/edit)  
- [Laparoscopy](https://docs.google.com/document/d/1qIq40jDvs2qIT-xPicYdL1NhyD2X-Qfvg-DyzYpW4uw/edit?tab=t.0)  
- [MONNIT Ultra Freezer Alarm System and Response Protocol](https://docs.google.com/document/d/1gc0syRTAqm2R6Wvq1qnistkWecmDGCaqGKsc1u0Lvkw/edit?tab=t.0#heading=h.oeue8dbow1pt)  
- [Processing Humeri](https://docs.google.com/document/d/1RdzdFwgW_9HrDVUfZViKBmYVifkIoGUm/edit)  
- [Tumor Scoring](https://docs.google.com/document/d/1eJ196ENHRCdLi2xSscxfbS17hG-rcFHxjAcqvbrW0so/edit?tab=t.0)  

# Stranding & Rescue Protocols
- [Sea Turtle Necropsy Coordination](https://docs.google.com/document/d/1fibIFvzBLYmghDQt6agLeEwZykzbRtR3rXSlhFW8hjg/edit?tab=t.0)  
- [Sea Turtle Stranding Communication & Coordination Protocol](https://docs.google.com/document/d/1Xc5bxxBqIzvRwAaNPlyPkz5i4YcZ8mNkUUPG1o1zEfg/edit?tab=t.0)  
- [Sea Turtle Stranding Intake Protocol](https://docs.google.com/document/d/16YFKdGMvC1_uAe6_Mt_uUjqMjciuFYJ3b35NssjJBBw/edit?tab=t.0)  

# Data & Analysis Protocols
- [ACDSee Photo Processing & Organization](https://docs.google.com/document/d/1he1RJR_QbCZ0yHOzgHJVohnfpbVu1U6UOkoFP6MDKlM/edit?tab=t.0)  
- [Database Nesting](https://docs.google.com/document/d/1gjnaHegDWCLaDhuljlOvvn8bk-Pvmrww6oEOBIcF_ZQ/edit?tab=t.0)  
- [Database Stranding](https://docs.google.com/document/d/1SVEUSiMrLXiA1o3VC1lHENOPBlKVnNTvC-64AEF4ag8/edit?tab=t.0)  
- [Dataloggers](https://docs.google.com/document/d/1ynFezkG-cvH0R0TGrZk1fzvn9kIorCsAH4-W8IstSOU/edit?tab=t.0)  
- [Entering Excavation Data in MTBAP Database](https://docs.google.com/document/d/1HkDlQpIXiYrrlFMPkxKBbmK4kpSplZnyj4NmGKfPXOw/edit?tab=t.0#heading=h.gk2n7gmqemro)  

