---
title: "Library Corner"
format: html
---

[NOAA Institutional Repository](https://repository.library.noaa.gov/){.external target="_blank"}

-   2025- [Marine debris impacts on Hawaiian green sea turtles (Chelonia mydas): High prevalence of hook-and-line fishing gear in strandings](https://www.sciencedirect.com/science/article/pii/S0025326X25003443){.external target="_blank"}

-   [Expanding the boundaries: regional connectivity in green turtle (Chelonia mydas) populations across Micronesia](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2025.1558792/full)

-   2024 [Abundance, production, and migrations of nesting green turtles at Rose Atoll, American Samoa, a regionally important rookery in the Central South Pacific Ocean](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2024.1403240/full){.external target="_blank"}

-   [Sex ratios of olive ridley sea turtles in the North Pacific high seas: implications for climate change research](https://www.int-res.com/abstracts/meps/v748/meps14703)

-   [\[Data Report\] 2013-2023 Final Report: Sea Turtle Surveys and Tracking in the Mariana Islands and Testing (MITT) study area](https://repository.library.noaa.gov/view/noaa/61493)

-   2023- [Population structure of Pacific green turtles: a new perspective from microsatellite DNA variation](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2023.1116941/full){.external target="_blank"}

-   [Evaluation of a long-term information tool reveals continued suitability for identifying bycatch hotspots but little effect on fisher location choice](https://www.sciencedirect.com/science/article/pii/S0006320723000125?via%3Dihub)

-   [Origins of green turtle fishery bycatch in the central Pacific revealed by mixed genetic markers](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2023.1112842/full)

-   [Non-random mating within an Island rookery of Hawaiian hawksbill turtles: demographic discontinuity at a small coastline scale](https://royalsocietypublishing.org/doi/10.1098/rsos.221547)

-   [Sequential scute growth layers reveal developmental histories of hawksbill sea turtles](https://link.springer.com/article/10.1007/s00227-023-04229-w)

-   2021- [Hawksbill Nesting in Hawai'i: 30-Year Dataset Reveals Recent Positive Trend for a Small, Yet Vital Population](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2021.770424/full)

-   [Species and population specific gene expression in blood transcriptomes of marine turtles](https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-021-07656-5)

-   [Interactions Among Hawaiian Hawksbills Suggest Prevalence of Social Behaviors in Marine Turtles](https://bioone.org/journals/chelonian-conservation-and-biology/volume-20/issue-2/CCB-1481.1/Interactions-Among-Hawaiian-Hawksbills-Suggest-Prevalence-of-Social-Behaviors-in/10.2744/CCB-1481.1.short)

-   2020- [Hawaiian hawksbills: a distinct and isolated nesting colony in the Central North Pacific Ocean revealed by mitochondrial DNA](https://link.springer.com/article/10.1007/s10592-020-01287-1){.external target="_blank"}

-   [Sea turtle tagging in the Mariana Islands Training and Testing (MITT) study area](https://repository.library.noaa.gov/view/noaa/23886){.external target="_blank"}

-   2019- [Potential limitations of behavioral plasticity and the role of egg relocation in climate change mitigation for a thermally sensitive endangered species](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.4774)

-   2018- [Environmental Warming and Feminization of One of the Largest Sea Turtle Populations in the World](https://www.cell.com/current-biology/fulltext/S0960-9822(17)31539-7?inline-read-more=){.external target="_blank"}

-   [Endangered Green Turtles (Chelonia mydas) of the Northern Mariana Islands: Nesting Ecology, Poaching, and Climate Concerns](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2017.00428/full)

-   [The Utility of Combining Stable Isotope and Hormone Analyses for Marine Megafauna Research](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2018.00338/full)

-   [Prevalence of polygyny in a critically endangered marine turtle population](https://www.sciencedirect.com/science/article/abs/pii/S0022098117304501#:~:text=Using%20six%20highly%20polymorphic%20microsatellite,a%20common%20mating%20structure%20for)

-   [Rookery contributions, movements and conservation needs of hawksbill turtles at foraging grounds in the eastern Pacific Ocean](https://www.int-res.com/abstracts/meps/v586/meps12391)

-   2017- [Demography of Marine Turtles in the Nearshore Environments of the Northern Mariana Islands](https://bioone.org/journals/pacific-science/volume-71/issue-3/71.3.3/Demography-of-Marine-Turtles-in-the-Nearshore-Environments-of-the/10.2984/71.3.3.full)

-   [Natal foraging philopatry in eastern Pacific hawksbill turtles](https://royalsocietypublishing.org/doi/10.1098/rsos.170153)

-   [Living on the Edge: Hawksbill turtle nesting and conservation along the Eastern Pacific Rim](https://www.scielo.cl/scielo.php?pid=S0718-560X2017000300007&script=sci_arttext)

-   2016- [Five Decades of Marine Megafauna Surveys from Micronesia](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2015.00116/full)

-   [An Ecosystem Services Perspective for the Oceanic Eastern Tropical Pacific: Commercial Fisheries, Carbon Storage, Recreational Fishing, and Biodiversity](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2016.00050/full)

-   [The Developmental biogeography of hawksbill sea turtles in the North Pacific](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.2034)

-   2012- [Age and growth rates of Hawaiian hawksbill turtles (Eretmochelys imbricata) using skeletochronology](https://link.springer.com/article/10.1007/s00227-012-2058-7)
